### ISSUE TITLE
`Html msg` instead of `Html Never`?

### ISSUE THREAD

**Issue by MattCheely** [andreasewering/travelm-agency#138]
In cases where the localized messages contain HTML, the generated functions return `List (Html Never)`, which can be made to work, but ends up requiring `Html.map never` frequently, as the localized content is frequently in a view that emits a specific `Msg` type. Is there a particular reason not to generate `List (Html msg)` instead to avoid having to call `Html.map`?

**Comment by andreasewering** [comment]
There is/was a reason - the opaque `I18n` type in the generated inline code is a record of functions.
When the functions use a type variable, it has to be used in `I18n` as well.
Now that is pretty awkward, because if you choose `msg` in `I18n msg` to be a certain `Msg` type, you cannot use it in a context with another message type. 

However: We could still use `Html.Never` in the `I18n` record and generate the `never`/`Html.map` calls for the accessor functions! I'll try to implement that.

**Comment by andreasewering** [comment]
Hmm so for the dynamic code generator, this is basically free, because the translation representation is just an array of string.
However, for the inline code generator, this is more tricky.

With `List.map (Html.map never)` we can generate functions like
```
text :
    { adminLink : String, role : String, username : String }
    -> List (Html.Attribute Never)
    -> I18n
    -> List (Html.Html msg)
text data htmlAttrs i18n =
    i18n.text_ data htmlAttrs
        |> List.map (Html.map never)
```

We cannot get rid of the `Never` in the Html Attributes though, since we can convert `Never -> msg` but not `msg -> Never`.
If someone has any ideas how to change the `I18n` implementation to avoid that problem, please comment :)

**Comment by andreasewering** [comment]
A valid way forward would be changing the Inline Code Generator to just use the same JSON format as the Dynamic Code Generator for over the wire, just inlined. I'm not a fan of that though, because it would bloat the size unnecessarily by needing to include elm-parser and quite a bit of parsing code unnecessarily.

Alternatively, we could make this work with a custom AST-like format in the I18n record.

Here is a possible implementation, let me know what you think

```
type alias I18n =
    { text_ :
        { adminLink : String, role : String, username : String }
        -> List H_or_T
    }


text :
    { adminLink : String, role : String, username : String }
    -> List (Html.Attribute msg)
    -> I18n
    -> List (Html.Html msg)
text data htmlAttrs i18n =
    i18n.text_ data
        |> interpretList (Array.fromList [ htmlAttrs ])

type H_or_T
    = H String Int (List (Html.Attribute Never)) (List H_or_T)
    | T String

interpret : Array (List (Html.Attribute msg)) -> H_or_T -> Html.Html msg
interpret extraAttrs h_or_t =
    let
        getAttrs i =
            Array.get i extraAttrs |> Maybe.withDefault []
    in
    case h_or_t of
        H tag id attrs children ->
            Html.node tag (List.map (Html.Attributes.map never) attrs ++ getAttrs id) <| interpretList extraAttrs children

        T txt ->
            Html.text txt


interpretList : Array (List (Html.Attribute msg)) -> List H_or_T -> List (Html.Html msg)
interpretList extraAttrs =
    List.map (interpret extraAttrs)




{-| `I18n` instance containing all values for the language En
-}
en : I18n
en =
    { text_ =
        \data ->
            case data.role of
                "admin" ->
                    [ T "Thanks for logging in. "
                    , H "a"
                        0
                        [ Html.Attributes.attribute "href" data.adminLink ]
                        [ T ("You (" ++ data.username ++ ") are not an admin.") ]
                    ]

                "normal" ->
                    [ T ("You (" ++ data.username ++ ") are not an admin.") ]

                _ ->
                    [ T "You are not logged in." ]
    }
```

**Comment by andreasewering** [comment]
Actually, it should be much more performant to just generate the accessor functions directly and not bother with the record approach.

I18n could just be a opaque wrapper around your generated custom language type and the functions could then pattern match on it.
Since the generated accessors are just functions and not records, there is no downside to using msg over Never.

**Comment by andreasewering** [comment]
Should _just work_ in the new version 3.3.0.
I decided for the last approach and used it to remove `never` calls from the Demo application.

Thanks for the suggestion @MattCheely 👍

**Comment by MattCheely** [comment]
Thanks, @andreasewering! You worked through the whole thing before I even had a chance to respond.  Not that I had a lot of insight to offer. We are using the dynamic version, which explains why I couldn't see the reasoning behind `Html Never`. I appreciate the explanation!
